/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("org.springframework.boot") version "2.7.1"
    id("io.freefair.lombok") version "6.5.0.2"
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    compileOnly("org.springframework.boot:spring-boot-configuration-processor")
//    implementation("net.mamoe:mirai-core-jvm:2.9.1")
    implementation("com.google.code.gson:gson")
    implementation("cn.hutool:hutool-http:5.8.3")
}

group = "com.para"
version = "0.0.1"
description = "tranzai"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
