/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("org.springframework.boot") version "2.7.1"
    id("io.freefair.lombok") version "6.5.0.2"
    kotlin("jvm") version "1.5.30" // 确保添加 Kotlin
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    compileOnly("org.springframework.boot:spring-boot-configuration-processor")
    // 使用mirai提供的pom，方便进行版本管理
    api(platform("net.mamoe:mirai-bom:2.9.1"))
    //mirai踩坑，与spring集成打包时必须指定运行平台(like -jvm).
    api("net.mamoe:mirai-core-api-jvm")     // 编译代码使用
    runtimeOnly("net.mamoe:mirai-core-jvm") // 运行时使用
    implementation("com.google.code.gson:gson")
    implementation("cn.hutool:hutool-http:5.8.3")
}

group = "com.para"
version = "0.0.1"
description = "tranzai"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}