# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      #    build in gradle
      - name: Print path
        run: pwd
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Authority
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew assemble
      # deploy...
      - name: SSH deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SOURCE: "build/libs/tranzai-0.0.1.jar"
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.HOST_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_PATH }}

