# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# 触发此工作流的事件
on:
  push:
    branches: [ master ]

# 执行的操作
jobs:
  build:
    #    构建操作执行的机器
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup java environment...
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # Build with maven...
      - name: Build with Maven
        run: mvn -B package -D skipTests --file pom.xml
      # list dir...
      - run: ls target
      # deploy...
      - name: SSH deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SOURCE: "target/tranzai.jar"
          SSH_PRIVATE_KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAuBuRghRBbSXCUC4daHhFcVfQaZS1cpvgRXUfpJAmK3TZfCDktng8
      MxRgADYoUGTQq2du8LQXswqLQxWQ1Wt50wKnEK+tSth/q3UL3qPp1NPlefH2X1hzBc6BDS
      4FpxUoN0eCsfPTxejrHeiekbd5aZVS8UDTvt6XnY+mQmtIpta+8ip/wzZTGWPzSJclDH+M
      KQ/dVD0DWXCbl0n/uctCr5/t6Nk4eVPIJy/hvZ6RKBjGJ/z+F5J8lJdUOWFn4UHhDg4Uj6
      LakbeQuUmouDBq3x6Rsk8Euj7qtZLr4pzuwNXjV2k4ECPqPaoEqAAqUc+xmctjJJhtpSaF
      PV5munov3mmPIQv2fArxkohaLOiVCYcb3m8tpUEg2TxQW4lnfODxdOblAW7NKxEDJv2AzS
      LkfbJgiNmaUGkRctMN1tl2gE+bi5qEnmOrwXiyEaik9Kipc8DwdEeY8sK6HnYlHLRWKiw/
      C+XZ+ctOydmKiSI9zhIr41Ke3/L9MVeT58JyRsFtAAAFiFmfPCVZnzwlAAAAB3NzaC1yc2
      EAAAGBALgbkYIUQW0lwlAuHWh4RXFX0GmUtXKb4EV1H6SQJit02Xwg5LZ4PDMUYAA2KFBk
      0KtnbvC0F7MKi0MVkNVredMCpxCvrUrYf6t1C96j6dTT5Xnx9l9YcwXOgQ0uBacVKDdHgr
      Hz08Xo6x3onpG3eWmVUvFA077el52PpkJrSKbWvvIqf8M2Uxlj80iXJQx/jCkP3VQ9A1lw
      m5dJ/7nLQq+f7ejZOHlTyCcv4b2ekSgYxif8/heSfJSXVDlhZ+FB4Q4OFI+i2pG3kLlJqL
      gwat8ekbJPBLo+6rWS6+Kc7sDV41dpOBAj6j2qBKgAKlHPsZnLYySYbaUmhT1eZrp6L95p
      jyEL9nwK8ZKIWizolQmHG95vLaVBINk8UFuJZ3zg8XTm5QFuzSsRAyb9gM0i5H2yYIjZml
      BpEXLTDdbZdoBPm4uahJ5jq8F4shGopPSoqXPA8HRHmPLCuh52JRy0ViosPwvl2fnLTsnZ
      iokiPc4SK+NSnt/y/TFXk+fCckbBbQAAAAMBAAEAAAGAASbbAC9UQXSNBKdlM7Qc6xqbiS
      2O/QqQmp6i9gqY0ojGm4oxJBsYdVFZUGcGVYpr68aX4RWfWFVmjaLi5xLnDjTkCqyurtsv
      4Ui4LEpmOhihROQIoIwTHCQwln6FNohhWgcugCKAXqqYXfWImGzHa6uteyjmqjkGRcwSRD
      Qbnj+Vrjop1nTOjEgdy4R2jN93ZwJcZhyDmtmjf4zM9sKYxjR/7ob9XXTyuZwJE4Ccc93D
      z5g7lrYp5VwVAM7lMXmSBiQI2z0cgjaH410VavkLtzzSr/OtO3tKQW8VY+pql729Qrvp+d
      uTdXGrdVCHRh5X/gehP+B3EzunMM9KTJdWRXZb8ZdBGdK6TNYlmpwspu1S+WThXfdV/rNr
      fDiE3ztoGyJVTyKFPe9mnU9rlpkYxh8/4Ek4JHkiJQ+fucNk6som5NxmS54o2O9pdvBl7f
      W+OYwbEGOScP+4Ubag7uBbbriq7a5tlwU5WbbfqDtIVPgKua8W4IKchRGohufjFeNBAAAA
      wQC+VuTMEt5GaNGOfFYa0czntbrpOYzoCEBkiSpQhmJGLSm1g3JgYkq38s5d2u1y7kKrMU
      1lWlcOb/A8C0sg8Gqxj42FXC15U6qx0t3S+Si71uBFDDNevRewNymxHsTIfAvNesc+SFmB
      VVZzZ0qi1DcPajyThnhQtSNzWyQNoIDwcbWLVzTOVL/ppMm8P0wFBZZWM3ZsKfvxQ4AnVi
      l2dO2X6IfcK0F7R5ehSwcNrbGlaX/t37qBT/le2aTSOBmgTpQAAADBAO5wbrGTM3NYpfGN
      H/cfLqUQwNyZfS+gIB+EPSSE36vTjiBB1PniXmWxC6CadmW5shdn8l0acnecl1HZB0Pppe
      klPLhxkRr2+C5+aVZRzbm/JHxNeftaZH9YfVyhUnZchfxhXBK5zChQawaeeyFDlvoQpZub
      YeD2bRFX9k8uwX0zOP1EReykeQmThecoPeJH2HlElZ/XBgRTJzPaqwk6zqrjcTpekN75+0
      HRT+E2tVrAHADnN3Vtdk6zta8CWf68iQAAAMEAxarDCwmRD/wzRoFag5ZswJX6zzzoOR+U
      b8H+CmPqxOE9MWzgG4fnndLyK57Hf65HtJNYHJZcxW9wwMMemcHzmvYFA/PgVfIuHJRHx7
      3zlHqahm/mVctJcLu/PVfKQQk0L9FvCklfojHj26qjAZxCw04QIkGzAgHdtAt1kjTlmYu5
      VpU18SaOcc0yMNTHARmFPvZahV6SkyyQxc0GP6AMcXw4/uLmy6LjzdLsipyCDK/pV+utmQ
      vAh14wSfmLT0zFAAAAEmxpY2hlbmdrdW5AY3NyZC5jbg==
          REMOTE_HOST: 121.5.179.246
          REMOTE_USER: root
          TARGET: /opt/tranzai


