# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# 触发此工作流的事件
on:
  push:
    branches: [ master ]

# 执行的操作
jobs:
  build:
    #    构建操作执行的机器
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup java environment...
      - name: Setup java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # Build with maven...
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # list dir..
      - run: ls target
      # deploy...
      - name: SSH deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SOURCE: "target/tranzai.jar"
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_SERVER__HOST }}
          REMOTE_USER: ${{ secrets.SERVER_NAME }}
          TARGET: /opt/tranzai


